name: Testes

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: windows-latest, ubuntu-latest, macos-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Executar testes
        run: python -m unittest discover unit_tests/
